MAIN_FILE="*.c"

COMPILER_FLAGS="-Werror -Wall -std=c99 -g"
PERF_COMP_FLAGS="-pg -O2"

LINKER_FLAGS=""


#gcc -o app $MAIN_FILE $COMPILER_FLAGS $LINKER_FLAGS
gcc -o app $MAIN_FILE $COMPILER_FLAGS $PERF_COMP_FLAGS $LINKER_FLAGS
